name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/libtest.yaml@main
    with:
      go-previous: "1.22"
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/librelease.yaml@main
